### ISSUE TITLE
Cannot see XCActionBar window (Xcode 6.2)

### ISSUE THREAD

**Issue by se-rg-os** [pdcgomes/XCActionBar#19]
Hi, I much appreciate work you have done, and I really lack such kind of tool.
But I am facing issue with XCActionBar when installed from Alcatraz. 
I see new menu items under **Window** menu, and when I use shortcut **Cmd+Shift+8** I see that menu blinks, but I cannot see XCActionBar itself. I would be happy helping you with any more additional information if I could only provide more details. I was thinking XCActionBar could be impacted with any other plugin, but I have removed all except Alcatraz and XCActionBar and restarted Xcode and still getting same behaviour. Shortcut invokes menu, I can invoke it manually as well, but cannot see bar still.

**Comment by pdcgomes** [comment]
Hi, thanks for the kind words!

Question:
Did you have a previous installation of XCActionBar (perhaps you've built it and installed it yourself) before installing it via Alcatraz?

I've actually seen this issue once - but I had to install it via Alcatraz, on top of an existing (manual) installation - hence my questions. A couple of friends of mine saw the same issue, but I haven't had anyone else raising the problem so I didn't look into it again. 
For some reason the plugin is failing to load the main window's nib file, and that's why you can't see the window.

I'm pretty sure it's not a conflict with _other_ plugins, so we can exclude that.

BTW: I just tried removing my current installation and installing it via Alcatraz and managed to reproduce it. I'll try to take some time to look into this and keep you posted.

Thanks for raising it.

**Comment by pdcgomes** [comment]
Ok, it seems like Alcatraz doesn't perform an `xcodebuild clean` before rebuilding a given plugin, and for reasons that I don't quite yet understand, when that happens, the xib files simply do not get compiled and ultimately do not end up getting copied over to their final destination.

I'm looking into possible solutions.

**Comment by se-rg-os** [comment]
@pdcgomes thank you for your quick reply. Looking forward for updates :) let me know anytime if you need my help or some testing from my side. Thank you again!

**Comment by pdcgomes** [comment]
Ok, temporary solution:

Open your terminal and run the following:

1. `cd ~/Library/Application Support/Alcatraz/Plug-ins/XCActionBar`
2. `xcodebuild clean && xcodebuild`

Had a friend of mine try this and it also worked for him.
Let me know if this solves the problem for you until I find a better solution.

**Comment by pdcgomes** [comment]
Ok, I think I fixed it, or at least I can't reproduce the problem anymore. 
Can you uninstall/install via Alcatraz and see if it's working for you now?

**Comment by se-rg-os** [comment]
@pdcgomes Yes, I can see it now! thank you!
I will test now more of it :) 
This will be a separate issue, but I have https://github.com/kattrali/cocoapods-xcode-plugin installed and it has "Create/Edit Podfile" submenu. When looking for it with XCActionBar my Xcode crashes on attempt to invoke it. But that is another story! Thank you for very quick fix of my issue :+1:

**Comment by pdcgomes** [comment]
Cool, great that it's working now!

Can you create a separate issue for the Cocoapods plugin problem? I'll take a look as soon as I have some spare time.

**Comment by se-rg-os** [comment]
Yes, here it goes: https://github.com/pdcgomes/XCActionBar/issues/20

**Comment by pdcgomes** [comment]
👍
